CREATE TABLE genres (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE movies (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR2(100) NOT NULL,
                        release_date DATE,
                        duration NUMBER,
                        score NUMBER(3, 1),
                        genre_id NUMBER REFERENCES genres(id)
);

CREATE TABLE actors (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(100) NOT NULL
);

CREATE TABLE movie_actors (
                              movie_id NUMBER REFERENCES movies(id),
                              actor_id NUMBER REFERENCES actors(id),
                              PRIMARY KEY (movie_id, actor_id)
);